<span style="font-size: 6px; float:right">Notebook created by <a style="text-decoration: none; color:#000;" href="https://s.zymon.org">Szymon Woźniak</a></span>
<br>
<center><font size="6"><b>Introduction to Computational Environment</b></font></center>
<br />
<center><font size="4"><b><u>Part II: SciPy stack</u></b></font></center>
<span style="float:right;"><b>Notebook version:</b> 0.3.5</span>

# Introduction

Since bare Python on its own is not sufficient for scientific computing, the second part of the `ice-lab` is devoted to the scientific computing tools for Python called `SciPy`.
In general, the name `SciPy` may refer to several related to each other but distinct entities.
The most important, from our perspective, is the `SciPy` stack, a collection of open-source software for scientific computing in Python.
It consists of many Python packages and in this notebook, you will learn about core components `numpy` and `matplotlib`.
There is also a Python package called `scipy` which is part of the `SciPy` stack and it provides many useful numerical routines.
`SciPy` might also refer to the community of people who use and develop `SciPy` stack and several conferences dedicated to scientific computing in Python.

In this notebook, you will learn about `NumPy` package which provides a high-performance multidimensional array object and tools for numerical computational, and `matplotlib` a package for plotting.

Before start working with this notebook, you should have a pretty good acquaintance with Python.

## Notebook setup

Before starting the main part of the notebook, execute the following cells to import necessary packages and functions.

In [1]:
# Easy path management
from pathlib import Path

# Simple HTTP requests
import requests

# NumPy package
import numpy as np

# Opening Waveform Audio File Format (*.wav)
from scipy.io import wavfile

# Opening images
from imageio import imread

# Audio class from ipython for displaying audio player in notebooks
from IPython.display import Audio

# tqdm for displaying nice progress bar
from tqdm.auto import tqdm

Since this notebook requires other files as well, download it from the web by executing the following cells.

In [2]:
def download(url, path):
    if not isinstance(path, Path):
        path = Path(path)
    if not path.is_file():
        r = requests.get(url)
        with open(path, "wb") as f:
            f.write(r.content)

In [3]:
urls = {
    "epic_sax_guy.wav": "http://sp-class.agh.edu.pl/samples/epic_sax_guy.wav",
}

for filename, url in tqdm(urls.items()):
    download(url, filename)

  0%|          | 0/1 [00:00<?, ?it/s]

Downloaded files should occur in the current working directory.
To verify it, let's print to the `stdout` output of the `ls -l` command which will list files in the current working directory.

In [ ]:
!ls -l

# Introduction to `NumPy` package

The `NumPy` package is the core of the `SciPy` stack.
It provides a high-level and high-performance multidimensional array data structure that can represent well-known linear algebra objects like vectors, matrices, etc., and routines for processing those arrays. 

NumPy is one of the basic and most commonly used packages for scientific computing with Python.
Among other things it contains:

- a powerful N-dimensional array object (vectors, matrices, and more)
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities


In order to use the `NumPy` package, you first need to make it accessible. 
To start using NumPy and all of the functions available in NumPy, you’ll need to import it. This can be easily done with this import statement:
```Python
import numpy as np
```
`numpy` is usually shortened to `np` to save time and also to keep code standardized so that anyone working with your code can easily understand and run it.



The material which is provided in this section is a rather basic understanding of this package, but it will be sufficient for your further work.
If you want to learn more about `numpy`, you can check out the official learning site [here](https://numpy.org/learn/).
If you are already familiar with MATLAB syntax, you might find the following tutorial [NumPy for MATLAB users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html) useful to get started with `NumPy`.

## NumPy array

An array is a central data structure of the NumPy library. It is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. The elements are all of the **same type**, referred to as the **array dtype**.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers.
The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of
the array along each dimension.

An array can also be referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. It can be thought of as an array of arrays. The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (**there’s no difference between row and column vectors** - important when using arrays in an algebraic sense), while a matrix refers to an array with two dimensions. For 3-D or higher-dimensional arrays, the term tensor is also commonly used.

The number of dimensions and items in an array is defined by its **shape**. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

```Python
[[0, 0, 0],
 [1, 1, 1]]
```

Your array has 2 axes. The first axis has a length of 2 and the second axis has a length of 3.

Just like in other Python container objects, the contents of an array can be accessed and modified by indexing or slicing the array. **Unlike the typical container objects, different arrays can share the same data, so changes made on one array might be visible in another.** (there is an example later)

## Python list vs NumPy array

In contrary to Python list, which can contain different data types within a single list, all of the elements in a NumPy array should be homogenous. That's because mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogenous. The advantages of NumPy arrays are that they are faster and more compact than Python lists, moreover an array consumes less memory and is convenient to use. 

## Creation of basic array

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

In [ ]:
arr = np.array([1, 2, 3])
print(arr, '\n')

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(arr2)

Besides creating an array from a sequence of elements there are many other functions to initialize an array:

- `np.zeros` - array of given shape filled with zeros

In [ ]:
arr = np.zeros(3)
print(arr)

- `np.empty` - array of given shape filled with random values depending on the state of the memory (a bit faster than zeros)

In [ ]:
arr = np.empty((3, 3))
print(arr)

- `np.ones` - array of given shape filled with ones

In [ ]:
arr = np.ones((3,2))
print(arr)

- `np.eye` - 2-D array with ones on the diagonal and zeros elsewhere

In [ ]:
arr = np.eye(3)
print(arr)

- `np.arange` - evenly spaced values within a given interval

In [ ]:
arr = np.arange(0, 100, 11)
print(arr)

- `np.linspace` - evenly spaced numbers over a specified interval

In [ ]:
arr = np.linspace(0, 100, 11)
print(arr)

## Indexing and silcing

You can index and slice NumPy arrays in the same ways you can slice Python lists. Checkout previous assignment if you are not sure you remember. Example of taking every row of the first column:

In [4]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, '\n')
      
print(arr[:, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 4 7]


Example of taking every column of the first row:

In [6]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, '\n')

print(arr[0, :], '\n')

print(arr[0])  # if you want to take all dimensions afterwards you dont need the colon ":"
               # if you want to take all previous dimensions you can write [..., 0]

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3] 

[1 2 3]


Example of taking rows 2 and 3 from columns 0 and 1:

In [7]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, '\n')

print(arr[2:4, 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[7 8]]


We can also index NumPy arrays using bolean or “mask” index arrays. Example of extracting every element of an array that is greater than 3:

In [8]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, '\n')

print(arr > 3, '\n')

print(arr[arr > 3])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[False False False]
 [ True  True  True]
 [ True  True  True]] 

[4 5 6 7 8 9]


We can also use logical indexing to change the values greater then 3 to 0.

In [9]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, '\n')

arr[arr > 3] = 0
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [0 0 0]
 [0 0 0]]


### Task#1

Use logical indexing to extract every element of arr that is greater than 3 and less than 7.

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, '\n')

"Your code goes in here"

### Task#2

Use slicing to flip arr up and down / left and right.

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, '\n')

"Your code goes in here"


## Array shape

- ndarray.ndim tells you the number of axes, or dimensions, of the array

- ndarray.size tells you the total number of elements of the array. This is the product of the elements of the array’s shape.

- ndarray.shape displays a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print('arr.ndim:', arr.ndim)
print('arr.size:', arr.size)
print('arr.shape:', arr.shape)

If we need to we can change the shape of the array using np.reshape.

In [ ]:
arr = np.arange(18)
print(arr)
print('arr.shape:', arr.shape, '\n')

arr = arr.reshape(6, 3)
print(arr)
print('arr.shape:', arr.shape, '\n')

arr = arr.reshape(2, 9)
print(arr)
print('arr.shape:', arr.shape, '\n')

arr = arr.reshape(2, 3, 3)
print(arr)
print('arr.shape:', arr.shape, '\n')

Sometimes might we need to insert an empty (singleton) dimension to an array. We can do that with np.reshape, np.expand_dims or np.newaxis. Example of inserting singleton dimension using reshape:

In [ ]:
arr = np.ones(3)
print(arr)
print('arr.shape:', arr.shape, '\n')

arr = arr.reshape(3, 1)
print(arr)
print('arr.shape:', arr.shape, '\n')

arr = np.ones(3)
arr = arr.reshape(1, 3)
print(arr)
print('arr.shape:', arr.shape, '\n')

Example of inserting a singleton dimension using np.expand_dims:

In [ ]:
arr = np.ones(3)
print(arr)
print('arr.shape:', arr.shape, '\n')

arr = np.expand_dims(arr, axis=1)
print(arr)
print('arr.shape:', arr.shape, '\n')

arr = np.ones(3)
arr = np.expand_dims(arr, axis=0)
print(arr)
print('arr.shape:', arr.shape, '\n')

### Task

Check how to insert a singleton dimension using np.newaxis, then use it on arr in two ways (along different axis). The results should be the same like in the two previous examples.

In [ ]:
arr = np.ones(3)
print(arr)
print('arr.shape:', arr.shape, '\n')

"Your code goes in here"

arr = arr[:, np.newaxis]
print(arr)
print('arr.shape:', arr.shape, '\n')

arr = np.ones(3)
arr = arr[np.newaxis, :]
print(arr)
print('arr.shape:', arr.shape, '\n')

We can also merge two arrays together using np.concatenate. The only requirement is that their dimensions must be compatible.

### Task

Check how does np.concatenate function work, then join arr and arr2 in two ways (along different axis).

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, '\n')

arr2 = np.ones(3)
print(arr2, '\n')

"Your code goes in here"

arr3 = np.concatenate((arr, arr2[np.newaxis, :]), axis=0)
print(arr3, '\n')

arr3 = np.concatenate((arr, arr2[:, np.newaxis]), axis=1)
print(arr3, '\n')

## Basic arithmetic operations:

Arithmetic operators on arrays apply elementwise.

| Operator | Operation                       
|:--------:| -------------------------------  
| +        | Addition                         
| -        | Subtraction
| /        | **Element-wise** division
| *        | **Element-wise** multiplication
| @        | **Matrix** multiplication
| %        | Modulo
| //       | Floor division
| **       | To the power of

Example of addition of two **arrays** (of equal shape):

In [ ]:
arr = np.eye(3)
print(arr, '\n')

arr2 = np.ones((3, 3))
print(arr2, '\n')

print(arr + arr2)

Example of element-wise multiplication of two **arrays** (of equal shape):

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, '\n')

arr2 = np.array([[1, 2, -1],
                 [0, 0, -2],
                 [-3, 0, 1]])
print(arr2, '\n')

print(arr * arr2)

Example of matrix multiplication of **two arays** (of compatible shape):

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr, '\n')

arr2 = np.eye(3)
print(arr2, '\n')

print(arr @ arr2)

Shape is **very important** for matrix multiplication of **two vectors**. Most of the time vectors will only have one dimension. Let's see what happens if we wanted to get [outer product](https://en.wikipedia.org/wiki/Outer_product) of two vectors that only have one dimension. (We can transpose an array using np.transpose or simply via np.T)

In [ ]:
arr = np.array([1, 2, 3])

print(arr)
print('arr.shape:', arr.shape, '\n')

arr2 = np.array([4, 5, 6])
print(arr2)
print('arr2.shape:', arr2.shape, '\n')

print(arr @ arr2.T)

We got [dot product (inner product)](https://en.wikipedia.org/wiki/Dot_product) instead.

### Task

Calculate the **outer product** of arr and arr2 in the cell below.

In [ ]:
arr = np.array([1, 2, 3])

print(arr)
print('arr.shape:', arr.shape, '\n')

arr2 = np.array([4, 5, 6])
print(arr2)
print('arr2.shape:', arr2.shape, '\n')

"Your code goes in here"



## Broadcasting

Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The only requirement is that the dimensions of the arrays must be compatible, for example when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you get a ValueError. Example of adding a number to the array (3 is repeated 3 times):

In [ ]:
arr = np.arange(3)
print(arr, '\n')

arr = arr + 3
print(arr + 3)

If we try to add a vector and an array that share a common dimension the vector will get broadcasted to the shape that allows for the operation.
Example of broadcasting for array and vector (vector is repeated 3 times):

In [ ]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(arr)
print('arr.shape:', arr.shape, '\n')

arr2 = np.arange(3)
print(arr2)
print('arr2.shape:', arr2.shape, '\n')

arr3 = arr + arr2
print(arr3)
print('arr3.shape:', arr3.shape, '\n')

### Task

Use broadcasting to create a square array whose rows are numbers 0-9. The array should look like this:  
<br>
\begin{bmatrix}
0 & 1 & 2 & \dotsb & 9\\
\vdots & \vdots & \vdots & \vdots & \vdots\\
0 & 1 & 2 & \dotsb & 9\\
\end{bmatrix}
<br>
Make use of the arr vector and **don't use any loops.**

In [ ]:
arr = np.arange(10)
print(arr, '\n')

"Your code goes in here."


## Some usefull functions

- np.min / np.max - minimum / maximum element of array (flattened by default)
- np.sum - sum of array elements over a given axis (flattened by default)
- np.sort - sorts an array
- np.transpose / np.T - transposes an array
- np.unique - unique elements of an array
- np.all / np.any - tests whether all /any array elements along a given axis evaluate to True
- np.isnan - tests element-wise for NaN
- np.isinf - tests element-wise for positive or negative infinity
- np.isfinite - tests element-wise for finiteness (not infinity or not Not a Number)
- np.exp - calculates the exponential of all elements in the array
- np.log / np.log10 - calculates the natural /base 10 logarithm of all elements in the array
- np.load / np.save - loads/ saves an array

If you need to use some of them check how do they work.

## Arrays sharing the same data ( ͡◉◞ ͜ʖ◟ ͡◉)

Sometimes different arrays can share the same data (as mentioned before), so changes made on one array are visible in another. You need to be aware of that because this can generate errors that may be hard to find. Here is an example:

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, '\n')

arr2 = arr.T

print(arr2, '\n')

arr[1, 1] = -1
print(arr, '\n')

print(arr2, '\n')

Since np.T doesn't return a copy of the array arr2 it still points to the same memory where arr is. We can avoid that using np.copy.

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr, '\n')

arr2 = arr.T.copy()

print(arr2, '\n')

arr[1, 1] = -1
print(arr, '\n')

print(arr2, '\n')

# SciPy - handling .wav files

## Introduction

The SciPy framework builds on top of the low-level NumPy framework for multidimensional arrays, and provides a large number of higher-level scientific algorithms. Some of the topics that SciPy covers are:

* Special functions ([scipy.special](http://docs.scipy.org/doc/scipy/reference/special.html))
* Integration ([scipy.integrate](http://docs.scipy.org/doc/scipy/reference/integrate.html))
* Optimization ([scipy.optimize](http://docs.scipy.org/doc/scipy/reference/optimize.html))
* Interpolation ([scipy.interpolate](http://docs.scipy.org/doc/scipy/reference/interpolate.html))
* Fourier Transforms ([scipy.fftpack](http://docs.scipy.org/doc/scipy/reference/fftpack.html))
* Signal Processing ([scipy.signal](http://docs.scipy.org/doc/scipy/reference/signal.html))
* Linear Algebra ([scipy.linalg](http://docs.scipy.org/doc/scipy/reference/linalg.html))
* Sparse Eigenvalue Problems ([scipy.sparse](http://docs.scipy.org/doc/scipy/reference/sparse.html))
* Statistics ([scipy.stats](http://docs.scipy.org/doc/scipy/reference/stats.html))
* Multi-dimensional image processing ([scipy.ndimage](http://docs.scipy.org/doc/scipy/reference/ndimage.html))
* File IO ([scipy.io](http://docs.scipy.org/doc/scipy/reference/io.html))

Each of these submodules provides a number of functions and classes that can be used to solve problems in their respective topics.

In this lecture we will look at how to use some of these subpackages.

To access the SciPy package in a Python program, we start by importing everything from the `scipy` module.

In [ ]:
from scipy import *

If we only need to use part of the SciPy framework you can selectively include only those modules we are interested in. For example, to include the linear algebra package under the name `la`, we can do:

In [ ]:
import scipy.linalg as la

## Handling .WAV files

To handle wav files you are going to use SciPy input/output wavfile module `scipy.io.wavfile`. It containes only two functions `read()` and `write()` that allows to save and load wav file. 

In [ ]:
from scipy.io import wavfile

To use function `read()` from wavfile module, you only have to specify filename with path to appropriate folder. `read()` returns the sample rate in samples per seconds and data from WAV file.

In [ ]:
fs, data = wavfile.read('epic_sax_guy.wav')

You can listen to audio you have loaded inside notebook using Audio class from IPython.display module. If data is multichannel, use a 2-D array of shape (Nchannels, Nsamples). It is important to specify correct sampling rate:

In [ ]:
from IPython.display import Audio
Audio(data.T, rate=fs)

To save wav file using `write()` function you need to specify filename for your file, sampling rate and data you want to save. To write multiple-channels, use a 2-D array of shape (Nsamples, Nchannels).

In [ ]:
wavfile.write('epic_sax_guy_2.wav', fs, data)

# matplotlib - 2D and 3D plotting in Python

## Introduction

Matplotlib is an excellent 2D and 3D graphics library for generating scientific figures. Some of the many advantages of this library include:

* Easy to get started
* Support for $\LaTeX$ formatted labels and texts
* Great control of every element in a figure, including figure size and DPI. 
* High-quality output in many formats, including PNG, PDF, SVG, EPS, and PGF.
* GUI for interactively exploring figures *and* support for headless generation of figure files (useful for batch jobs).

One of the key features of matplotlib that I would like to emphasize, and that I think makes matplotlib highly suitable for generating figures for scientific publications is that all aspects of the figure can be controlled *programmatically*. This is important for reproducibility and convenient when one needs to regenerate the figure with updated data or change its appearance. 

More information at the Matplotlib web page: http://matplotlib.org/

In [ ]:
import matplotlib
import matplotlib.pyplot as plt

In [ ]:
import numpy as np

## MATLAB-like API

The easiest way to get started with plotting using matplotlib is often to use the MATLAB-like API provided by matplotlib. 

It is designed to be compatible with MATLAB's plotting functions, so it is easy to get started with if you are familiar with MATLAB.

To use this API from matplotlib, we need to include the symbols in the `pyplot` module: 

### Simple plot

Generating visualizations with `pyplot` is very quick:

In [ ]:
plt.plot([1, 2, 3, 4])
plt.show()

You may be wondering why the x-axis ranges from 0-3 and the y-axis from 1-4. If you provide a single list or array to the plot() command, matplotlib assumes it is a sequence of y values, and automatically generates the x values for you. Since python ranges start with 0, the default x vector has the same length as y but starts with 0. Hence the x data are [0,1,2,3].

`plot()` is very versatile. It can take an arbitrary number of arguments. For example you can plot x versus y by:

In [ ]:
x = np.linspace(0, 5, 10)
y = x ** 2

In [ ]:
plt.plot(x, y)

You can notice, that IPython kernel of Jupyter notebook renders the plot out cell even if `show()` function of plot object is not called. The `show()` function causes the figure to be displayed below in[] cell without out[] with number.

### Formating your plot

For every x, y pair of arguments, `plot()` function can take third optional argument, wich is the format string that indicates the color and line type of the plot. The symbols and letters are corresponding to MATLABs, and you can concatenate a color string with a line style string. The deafault is 'b-' which means blue solid line. For example, to plot, you can plot above with red circles:

In [ ]:
plt.plot(x, y, 'r.')

Moreover most of the plotting related functions in MATLAB are covered by the `pyplot` module. For example `title`, `xlabel`, `ylabel`, `xlim`, `ylim`, `figsize`, `scatter`, `subplot`, `fontsize` and others. You can also plot multiple functions on single plot:

In [ ]:
plt.figure(figsize=(8,5), dpi=100)          #set figure size to 8 x 5 inches and 100 dpi (dots per inch)
plt.plot(x, y, 'bs', x/2, 2*y, 'g^')        #plot y vs x and y*2 vs x/2
plt.xlabel('x')                             #set x axis label   
plt.ylabel('y')                             #set y axis label 
plt.title('title', fontsize=18)             #set figure title with font size = 18
plt.xlim(right=5)                           #set the right limit of x axis only
plt.ylim((0,50))                            #set y axis limits
plt.show()                      

### Task

Plot audio from file `epicsaxguy.wav` on single plot. One channel should be red, and the second one should be green colour. Add labels and a title with a minimum font size of 15. Total figure size should be 1000x600 pixels.

In [ ]:
# Your code goes in here

fs, y = wavfile.read('epic_sax_guy.wav')


The good thing about the pylab MATLAB-style API is that it is easy to get started with if you are familiar with MATLAB, and it has a minumum of coding overhead for simple plots. 

However, I'd encourrage not using the MATLAB compatible API for anything but the simplest figures.

Instead, I recommend learning and using matplotlib's object-oriented plotting API. It is remarkably powerful. For advanced figures with subplots, insets and other components it is very nice to work with. 

## The matplotlib object-oriented API

The main idea with object-oriented programming is to have objects that one can apply functions and actions on, and no object or program states should be global (such as the MATLAB-like API). The real advantage of this approach becomes apparent when more than one figure is created, or when a figure contains more than one subplot. 

To use the object-oriented API we start out very much like in the previous example, but instead of creating a new global figure instance we store a reference to the newly created figure instance in the `fig` variable, and from it we create a new axis instance `axes` using the `add_axes` method in the `Figure` class instance `fig`:

In [ ]:
x = np.linspace(0, 5, 10)
y = x ** 2

In [ ]:
fig = plt.figure()

axes = fig.add_axes([0.1, 0.1, 0.8, 0.8]) # left, bottom, width, height (range 0 to 1)

axes.plot(x, y, 'r.')

axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title', fontsize = 18);

Although a little bit more code is involved, the advantage is that we now have full control of where the plot axes are placed, and we can easily add more than one axis to the figure:

In [ ]:
fig = plt.figure()

axes1 = fig.add_axes([0.1, 0.1, 0.8, 0.8]) # main axes
axes2 = fig.add_axes([0.2, 0.5, 0.4, 0.3]) # inset axes

# main figure
axes1.plot(x, y, 'r')
axes1.set_xlabel('x')
axes1.set_ylabel('y')
axes1.set_title('title')

# insert
axes2.plot(y, x, 'g')
axes2.set_xlabel('y')
axes2.set_ylabel('x')
axes2.set_title('insert title');

If we don't care about being explicit about where our plot axes are placed in the figure canvas, then we can use one of the many axis layout managers in matplotlib. My favorite is `subplots`, which can be used like this:

In [ ]:
fig, axes = plt.subplots()

axes.plot(x, y, 'r')
axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title');

In [ ]:
fig, axes = plt.subplots(nrows=1, ncols=2)

for ax in axes:
    ax.plot(x, y, 'r')
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_title('title')

That was easy, but it isn't so pretty with overlapping figure axes and labels, right?

We can deal with that by using the `fig.tight_layout` method, which automatically adjusts the positions of the axes on the figure canvas so that there is no overlapping content:

In [ ]:
fig, axes = plt.subplots(nrows=1, ncols=2)

for ax in axes:
    ax.plot(x, y, 'r')
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_title('title')
    
fig.tight_layout()

### Saving figures

To save a figure to a file we can use the `savefig` method in the `Figure` class:

In [ ]:
fig.savefig("filename.png")

Here we can also optionally specify the DPI and choose between different output formats:

In [ ]:
fig.savefig("filename.png", dpi=200)

#### What formats are available and which ones should be used for best quality?

Matplotlib can generate high-quality output in a number formats, including PNG, JPG, EPS, SVG, PGF and PDF. For scientific papers, I recommend using PDF whenever possible. (LaTeX documents compiled with `pdflatex` can include PDFs using the `includegraphics` command). In some cases, PGF can also be good alternative.

### Legends, labels and titles

Now that we have covered the basics of how to create a figure canvas and add axes instances to the canvas, let's look at how decorate a figure with titles, axis labels, and legends.

**Figure titles**

A title can be added to each axis instance in a figure. To set the title, use the `set_title` method in the axes instance:

In [ ]:
ax.set_title("title");

**Axis labels**

Similarly, with the methods `set_xlabel` and `set_ylabel`, we can set the labels of the X and Y axes:

In [ ]:
ax.set_xlabel("x")
ax.set_ylabel("y");

**Legends**

Legends for curves in a figure can be added in two ways. One method is to use the `legend` method of the axis object and pass a list/tuple of legend texts for the previously defined curves:

In [ ]:
ax.legend(["curve1", "curve2", "curve3"]);

The method described above follows the MATLAB API. It is somewhat prone to errors and unflexible if curves are added to or removed from the figure (resulting in a wrongly labelled curve).

A better method is to use the `label="label text"` keyword argument when plots or other objects are added to the figure, and then using the `legend` method without arguments to add the legend to the figure: 

In [ ]:
ax.plot(x, x**2, label="curve1")
ax.plot(x, x**3, label="curve2")
ax.legend();

The advantage with this method is that if curves are added or removed from the figure, the legend is automatically updated accordingly.

The `legend` function takes an optional keyword argument `loc` that can be used to specify where in the figure the legend is to be drawn. The allowed values of `loc` are numerical codes for the various places the legend can be drawn. See http://matplotlib.org/users/legend_guide.html#legend-location for details. Some of the most common `loc` values are:

The following figure shows how to use the figure title, axis labels and legends described above:

In [ ]:
fig, ax = plt.subplots()

ax.plot(x, x**2, label="y = x**2")
ax.plot(x, x**3, label="y = x**3")
ax.legend(loc=2); # upper left corner
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_title('title');

#### Line and marker styles

To change the line width, we can use the `linewidth` or `lw` keyword argument. The line style can be selected using the `linestyle` or `ls` keyword arguments:

In [ ]:
fig, ax = plt.subplots(figsize=(12,6))

ax.plot(x, x+1, color="blue", linewidth=0.25)
ax.plot(x, x+2, color="blue", linewidth=0.50)
ax.plot(x, x+3, color="blue", linewidth=1.00)
ax.plot(x, x+4, color="blue", linewidth=2.00)

# possible linestype options ‘-‘, ‘--’, ‘-.’, ‘:’, ‘steps’
ax.plot(x, x+5, color="red", lw=2, linestyle='-')
ax.plot(x, x+6, color="red", lw=2, ls='-.')
ax.plot(x, x+7, color="red", lw=2, ls=':')

# custom dash
line, = ax.plot(x, x+8, color="black", lw=1.50)
line.set_dashes([5, 10, 15, 10]) # format: line length, space length, ...

# possible marker symbols: marker = '+', 'o', '*', 's', ',', '.', '1', '2', '3', '4', ...
ax.plot(x, x+ 9, color="green", lw=2, ls='--', marker='+')
ax.plot(x, x+10, color="green", lw=2, ls='--', marker='o')
ax.plot(x, x+11, color="green", lw=2, ls='--', marker='s')
ax.plot(x, x+12, color="green", lw=2, ls='--', marker='1')

# marker size and color
ax.plot(x, x+13, color="purple", lw=1, ls='-', marker='o', markersize=2)
ax.plot(x, x+14, color="purple", lw=1, ls='-', marker='o', markersize=4)
ax.plot(x, x+15, color="purple", lw=1, ls='-', marker='o', markersize=8, markerfacecolor="red")
ax.plot(x, x+16, color="purple", lw=1, ls='-', marker='s', markersize=8, 
        markerfacecolor="yellow", markeredgewidth=2, markeredgecolor="blue");

### Control over axis appearance

The appearance of the axes is an important aspect of a figure that we often need to modify to make a publication quality graphics. We need to be able to control where the ticks and labels are placed, modify the font size and possibly the labels used on the axes. In this section we will look at controling those properties in a matplotlib figure.

#### Plot range

The first thing we might want to configure is the ranges of the axes. We can do this using the `set_ylim` and `set_xlim` methods in the axis object, or `axis('tight')` for automatrically getting "tightly fitted" axes ranges:

In [ ]:
fig, axes = plt.subplots(1, 3, figsize=(12, 4))

axes[0].plot(x, x**2, x, x**3)
axes[0].set_title("default axes ranges")

axes[1].plot(x, x**2, x, x**3)
axes[1].axis('tight')
axes[1].set_title("tight axes")

axes[2].plot(x, x**2, x, x**3)
axes[2].set_ylim([0, 60])
axes[2].set_xlim([2, 5])
axes[2].set_title("custom axes range");

#### Logarithmic scale

It is also possible to set a logarithmic scale for one or both axes. This functionality is in fact only one application of a more general transformation system in Matplotlib. Each of the axes' scales are set seperately using `set_xscale` and `set_yscale` methods which accept one parameter (with the value "log" in this case):

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(10,4))
      
axes[0].plot(x, x**2, x, np.exp(x))
axes[0].set_title("Normal scale")

axes[1].plot(x, x**2, x, np.exp(x))
axes[1].set_yscale("log")
axes[1].set_title("Logarithmic scale (y)");

#### Axis position adjustments

Unfortunately, when saving figures the labels are sometimes clipped, and it can be necessary to adjust the positions of axes a little bit. This can be done using `subplots_adjust`:

In [ ]:
fig, ax = plt.subplots(1, 1)
      
ax.plot(x, x**2, x, np.exp(x))
ax.set_yticks([0, 50, 100, 150])

ax.set_title("title")
ax.set_xlabel("x")
ax.set_ylabel("y")

fig.subplots_adjust(left=0.15, right=.9, bottom=0.1, top=0.9);

### Other 2D plot styles

In addition to the regular `plot` method, there are a number of other functions for generating different kind of plots. See the matplotlib plot gallery for a complete list of available plot types: http://matplotlib.org/gallery.html. Some of the more useful ones are show below:

In [ ]:
n = np.array([0,1,2,3,4,5])
xx = np.linspace(-0.75, 1., 100)

In [ ]:
fig, axes = plt.subplots(1, 4, figsize=(12,3))

axes[0].scatter(xx, xx + 0.25*np.random.randn(len(xx)))
axes[0].set_title("scatter")

axes[1].step(n, n**2, lw=2)
axes[1].set_title("step")

axes[2].bar(n, n**2, align="center", width=0.5, alpha=0.5)
axes[2].set_title("bar")

axes[3].fill_between(x, x**2, x**3, color="green", alpha=0.5);
axes[3].set_title("fill_between");

In [ ]:
# polar plot using add_axes and polar projection
fig = plt.figure()
ax = fig.add_axes([0.0, 0.0, .6, .6], polar=True)
t = np.linspace(0, 2 * np.pi, 100)
ax.plot(t, t, color='blue', lw=3);

In [ ]:
# A histogram
n = np.random.randn(100000)
fig, axes = plt.subplots(1, 2, figsize=(12,4))

axes[0].hist(n)
axes[0].set_title("Default histogram")
axes[0].set_xlim((min(n), max(n)))

axes[1].hist(n, cumulative=True, bins=50)
axes[1].set_title("Cumulative detailed histogram")
axes[1].set_xlim((min(n), max(n)));

### Colormap and contour figures

Colormaps and contour figures are useful for plotting functions of two variables. In most of these functions we will use a colormap to encode one dimension of the data. There are a number of predefined colormaps. It is relatively straightforward to define custom colormaps. For a list of pre-defined colormaps, see: http://www.scipy.org/Cookbook/Matplotlib/Show_colormaps

In [ ]:
alpha = 0.7
phi_ext = 2 * np.pi * 0.5

def flux_qubit_potential(phi_m, phi_p):
    return 2 + alpha - 2 * np.cos(phi_p) * np.cos(phi_m) - alpha * np.cos(phi_ext - 2*phi_p)

In [ ]:
phi_m = np.linspace(0, 2*np.pi, 100)
phi_p = np.linspace(0, 2*np.pi, 100)
X,Y = np.meshgrid(phi_p, phi_m)
Z = flux_qubit_potential(X, Y).T

#### pcolor

In [ ]:
fig, ax = plt.subplots()

p = ax.pcolor(X/(2*np.pi), Y/(2*np.pi), Z, cmap=matplotlib.cm.RdBu, vmin=abs(Z).min(), vmax=abs(Z).max())
cb = fig.colorbar(p, ax=ax)

#### imshow

In [ ]:
fig, ax = plt.subplots()

im = ax.imshow(Z, cmap=matplotlib.cm.RdBu, vmin=abs(Z).min(), vmax=abs(Z).max(), extent=[0, 1, 0, 1])
im.set_interpolation('bilinear')

cb = fig.colorbar(im, ax=ax)

### Task

Create figure with three subplots in rows. In the first subplot draw both channels of the entire audio file `epic_sax_guy.wav`. In the second and third subplot put samples from 500 to 2000 from each channel separatly. Mark each occurrence of 0 with red dot. Add title and labels for each subplot independently. Make sure that there are no overlapping elements.

In [ ]:
fs, y = wavfile.read('epic_sax_guy.wav')


# Summary

When finishing this notebook, you should be familiar with the basic `numpy` data structure `numpy.ndarray`, its methods and properties, and basic routines for processing such objects.
Additionally, you should have the ability to plot figures at least with 1D data with `matplotlib` package, including a detailed description of the figure (labels, title, etc.).